-- Item definition as associative array aka LUA table
-- > mass: kg
itemsTable = 
{
    ["10 counter"] = {["mass"] = 9.93},
    ["2 counter"] = {["mass"] = 9.93},
    ["3 counter"] = {["mass"] = 9.93},
    ["3d printer m"] = {["mass"] = 2000.00},
    ["5 counter"] = {["mass"] = 9.93},
    ["7 counter"] = {["mass"] = 9.93},
    ["acanthite"] = {["mass"] = 7.20},
    ["adjustor l"] = {["mass"] = 1180.00},
    ["adjustor m"] = {["mass"] = 220.38},
    ["adjustor s"] = {["mass"] = 42.58},
    ["adjustor xs"] = {["mass"] = 22.70},
    ["advanced antenna s"] = {["mass"] = 389.74},
    ["advanced anti-gravity core"] = {["mass"] = 117.05},
    ["advanced anti-matter capsule"] = {["mass"] = 24.88},
    ["advanced anti-matter core unit"] = {["mass"] = 107.08},
    ["advanced burner"] = {["mass"] = 48.50},
    ["advanced casing l"] = {["mass"] = 394.80},
    ["advanced casing m"] = {["mass"] = 56.70},
    ["advanced casing s"] = {["mass"] = 8.40},
    ["advanced casing xl"] = {["mass"] = 2760.00},
    ["advanced casing xs"] = {["mass"] = 1.50},
    ["advanced chemical container l"] = {["mass"] = 1270.00},
    ["advanced chemical container m"] = {["mass"] = 235.25},
    ["advanced chemical container s"] = {["mass"] = 48.85},
    ["advanced chemical container xl"] = {["mass"] = 7190.00},
    ["advanced combustion chamber m"] = {["mass"] = 1760.00},
    ["advanced combustion chamber s"] = {["mass"] = 369.50},
    ["advanced combustion chamber xs"] = {["mass"] = 163.51},
    ["advanced component"] = {["mass"] = 2.51},
    ["advanced connector"] = {["mass"] = 4.18},
    ["advanced control system l"] = {["mass"] = 1410.00},
    ["advanced control system m"] = {["mass"] = 272.97},
    ["advanced control system s"] = {["mass"] = 59.35},
    ["advanced core system m"] = {["mass"] = 139.61},
    ["advanced electronics"] = {["mass"] = 5.45},
    ["advanced explosive module"] = {["mass"] = 19.04},
    ["advanced firing system l"] = {["mass"] = 9410.00},
    ["advanced firing system m"] = {["mass"] = 1760.00},
    ["advanced firing system s"] = {["mass"] = 369.50},
    ["advanced firing system xs"] = {["mass"] = 163.51},
    ["advanced fixation"] = {["mass"] = 1.21},
    ["advanced glass"] = {["mass"] = 2.60},
    ["advanced hydraulics"] = {["mass"] = 29.02},
    ["advanced injector"] = {["mass"] = 20.45},
    ["advanced ionic chamber l"] = {["mass"] = 11370.00},
    ["advanced ionic chamber m"] = {["mass"] = 8640.00},
    ["advanced laser chamber l"] = {["mass"] = 2380.00},
    ["advanced laser chamber m"] = {["mass"] = 429.89},
    ["advanced laser chamber s"] = {["mass"] = 87.02},
    ["advanced laser chamber xs"] = {["mass"] = 36.51},
    ["advanced led"] = {["mass"] = 1.32},
    ["advanced magnet"] = {["mass"] = 63.89},
    ["advanced magnetic rail l"] = {["mass"] = 11160.00},
    ["advanced magnetic rail m"] = {["mass"] = 2120.00},
    ["advanced magnetic rail s"] = {["mass"] = 451.89},
    ["advanced magnetic rail xs"] = {["mass"] = 204.70},
    ["advanced mechanical sensor xs"] = {["mass"] = 100.99},
    ["advanced missile silo l"] = {["mass"] = 7360.00},
    ["advanced missile silo m"] = {["mass"] = 1460.00},
    ["advanced missile silo s"] = {["mass"] = 327.52},
    ["advanced missile silo xs"] = {["mass"] = 157.51},
    ["advanced motherboard m"] = {["mass"] = 109.19},
    ["advanced optics"] = {["mass"] = 10.18},
    ["advanced pipe"] = {["mass"] = 2.19},
    ["advanced power system"] = {["mass"] = 64.90},
    ["advanced processor"] = {["mass"] = 15.56},
    ["advanced quantum alignment unit"] = {["mass"] = 35.78},
    ["advanced quantum barrier"] = {["mass"] = 43.38},
    ["advanced quantum core"] = {["mass"] = 11.24},
    ["advanced reinforced frame l"] = {["mass"] = 3440.00},
    ["advanced reinforced frame m"] = {["mass"] = 494.08},
    ["advanced reinforced frame s"] = {["mass"] = 73.34},
    ["advanced reinforced frame xs"] = {["mass"] = 13.24},
    ["advanced screen xs"] = {["mass"] = 10.73},
    ["advanced screw"] = {["mass"] = 8.14},
    ["advanced singularity container"] = {["mass"] = 46.22},
    ["advanced solid warhead"] = {["mass"] = 46.43},
    ["advanced standard frame l"] = {["mass"] = 961.45},
    ["advanced standard frame m"] = {["mass"] = 138.25},
    ["advanced standard frame s"] = {["mass"] = 20.65},
    ["advanced standard frame xs"] = {["mass"] = 3.85},
    ["ag-li reinforced glass"] = {["mass"] = 2.80},
    ["aileron m"] = {["mass"] = 3410.00},
    ["aileron s"] = {["mass"] = 638.30},
    ["aileron xs"] = {["mass"] = 122.40},
    ["airlock"] = {["mass"] = 4200.00},
    ["al-fe alloy"] = {["mass"] = 7.50},
    ["al-li alloy"] = {["mass"] = 2.50},
    ["aluminium honeycomb"] = {["mass"] = 27.00},
    ["aluminium scrap"] = {["mass"] = 2.70},
    ["ammo container l"] = {["mass"] = 12880.00},
    ["ammo container m"] = {["mass"] = 6440.00},
    ["ammo container s"] = {["mass"] = 1170.00},
    ["ammo container xs"] = {["mass"] = 216.15},
    ["and operator"] = {["mass"] = 13.27},
    ["antenna l"] = {["mass"] = 6850.00},
    ["antenna m"] = {["mass"] = 902.74},
    ["antenna s"] = {["mass"] = 130.06},
    ["anti-gravity generator l"] = {["mass"] = 550870.00},
    ["anti-gravity generator m"] = {["mass"] = 137720.00},
    ["anti-gravity generator s"] = {["mass"] = 27130.00},
    ["anti-gravity pulsor"] = {["mass"] = 6210.00},
    ["armored window l"] = {["mass"] = 377.28},
    ["armored window m"] = {["mass"] = 188.64},
    ["armored window s"] = {["mass"] = 94.32},
    ["armored window xs"] = {["mass"] = 47.16},
    ["assembly line l"] = {["mass"] = 15380.00},
    ["assembly line m"] = {["mass"] = 2800.00},
    ["assembly line s"] = {["mass"] = 522.14},
    ["assembly line xl"] = {["mass"] = 86290.00},
    ["assembly line xs"] = {["mass"] = 100.93},
    ["atmospheric airbrake l"] = {["mass"] = 1500.00},
    ["atmospheric airbrake m"] = {["mass"] = 285.25},
    ["atmospheric airbrake s"] = {["mass"] = 55.55},
    ["atmospheric engine l"] = {["mass"] = 16930.00},
    ["atmospheric engine m"] = {["mass"] = 2980.00},
    ["atmospheric engine s"] = {["mass"] = 539.99},
    ["atmospheric engine xs"] = {["mass"] = 101.88},
    ["atmospheric fuel tank l"] = {["mass"] = 5480.00},
    ["atmospheric fuel tank m"] = {["mass"] = 988.67},
    ["atmospheric fuel tank s"] = {["mass"] = 182.67},
    ["atmospheric fuel tank xs"] = {["mass"] = 35.03},
    ["bagged plant a"] = {["mass"] = 3.52},
    ["bagged plant b"] = {["mass"] = 3.52},
    ["barrier corner"] = {["mass"] = 14.65},
    ["barrier m"] = {["mass"] = 14.65},
    ["barrier s"] = {["mass"] = 14.65},
    ["basic antenna s"] = {["mass"] = 314.20},
    ["basic antenna xs"] = {["mass"] = 60.44},
    ["basic anti-matter capsule"] = {["mass"] = 24.00},
    ["basic burner"] = {["mass"] = 50.20},
    ["basic casing s"] = {["mass"] = 7.70},
    ["basic casing xs"] = {["mass"] = 1.40},
    ["basic chemical container l"] = {["mass"] = 1340.00},
    ["basic chemical container m"] = {["mass"] = 239.38},
    ["basic chemical container s"] = {["mass"] = 43.67},
    ["basic chemical container xl"] = {["mass"] = 7750.00},
    ["basic chemical container xs"] = {["mass"] = 8.13},
    ["basic combustion chamber l"] = {["mass"] = 9340.00},
    ["basic combustion chamber m"] = {["mass"] = 1710.00},
    ["basic combustion chamber s"] = {["mass"] = 319.35},
    ["basic combustion chamber xs"] = {["mass"] = 60.65},
    ["basic component"] = {["mass"] = 2.25},
    ["basic connector"] = {["mass"] = 3.75},
    ["basic control system m"] = {["mass"] = 247.97},
    ["basic control system s"] = {["mass"] = 47.63},
    ["basic control system xs"] = {["mass"] = 9.25},
    ["basic core system s"] = {["mass"] = 23.57},
    ["basic core system xs"] = {["mass"] = 4.43},
    ["basic electric engine m"] = {["mass"] = 1930.00},
    ["basic electric engine s"] = {["mass"] = 377.75},
    ["basic electronics"] = {["mass"] = 5.22},
    ["basic explosive module"] = {["mass"] = 18.72},
    ["basic firing system xs"] = {["mass"] = 60.65},
    ["basic fixation"] = {["mass"] = 1.12},
    ["basic gas cylinder m"] = {["mass"] = 427.88},
    ["basic gas cylinder s"] = {["mass"] = 81.38},
    ["basic gas cylinder xs"] = {["mass"] = 15.68},
    ["basic hydraulics"] = {["mass"] = 28.95},
    ["basic injector"] = {["mass"] = 20.30},
    ["basic ionic chamber l"] = {["mass"] = 1620.00},
    ["basic ionic chamber m"] = {["mass"] = 2070.00},
    ["basic ionic chamber s"] = {["mass"] = 391.60},
    ["basic ionic chamber xl"] = {["mass"] = 61230.00},
    ["basic ionic chamber xs"] = {["mass"] = 75.10},
    ["basic led"] = {["mass"] = 1.25},
    ["basic magnet"] = {["mass"] = 63.30},
    ["basic mechanical sensor xs"] = {["mass"] = 35.96},
    ["basic mobile panel l"] = {["mass"] = 2830.00},
    ["basic mobile panel m"] = {["mass"] = 536.00},
    ["basic mobile panel s"] = {["mass"] = 103.00},
    ["basic mobile panel xl"] = {["mass"] = 15160.00},
    ["basic mobile panel xs"] = {["mass"] = 20.00},
    ["basic optics"] = {["mass"] = 9.74},
    ["basic pipe"] = {["mass"] = 2.40},
    ["basic power system"] = {["mass"] = 60.00},
    ["basic power transformer m"] = {["mass"] = 1020.00},
    ["basic processor"] = {["mass"] = 14.84},
    ["basic quantum core unit"] = {["mass"] = 10.72},
    ["basic reinforced frame l"] = {["mass"] = 3320.00},
    ["basic reinforced frame m"] = {["mass"] = 476.00},
    ["basic reinforced frame s"] = {["mass"] = 70.84},
    ["basic reinforced frame xl"] = {["mass"] = 23200.00},
    ["basic reinforced frame xs"] = {["mass"] = 12.88},
    ["basic robotic arm l"] = {["mass"] = 4930.00},
    ["basic robotic arm m"] = {["mass"] = 927.00},
    ["basic robotic arm xl"] = {["mass"] = 26700.00},
    ["basic screen m"] = {["mass"] = 115.17},
    ["basic screen s"] = {["mass"] = 21.07},
    ["basic screw"] = {["mass"] = 8.05},
    ["basic singularity container"] = {["mass"] = 45.36},
    ["basic standard frame l"] = {["mass"] = 1080.00},
    ["basic standard frame m"] = {["mass"] = 155.40},
    ["basic standard frame s"] = {["mass"] = 23.10},
    ["basic standard frame xs"] = {["mass"] = 4.20},
    ["bauxite"] = {["mass"] = 1.28},
    ["bay window xl"] = {["mass"] = 5090.00},
    ["bed"] = {["mass"] = 128.94},
    ["bench"] = {["mass"] = 22.33},
    ["biological matter"] = {["mass"] = 1.00},
    ["bonsai"] = {["mass"] = 902.04},
    ["brick honeycomb"] = {["mass"] = 27.57},
    ["brick"] = {["mass"] = 1.92},
    ["cable model a m"] = {["mass"] = 14.10},
    ["cable model a s"] = {["mass"] = 14.10},
    ["cable model b m"] = {["mass"] = 14.10},
    ["cable model b s"] = {["mass"] = 14.10},
    ["cable model c m"] = {["mass"] = 14.10},
    ["cable model c s"] = {["mass"] = 14.10},
    ["calcium honeycomb"] = {["mass"] = 15.50},
    ["calcium reinforced copper"] = {["mass"] = 8.10},
    ["calcium scrap"] = {["mass"] = 1.55},
    ["cannon agile kinetic ammo l"] = {["mass"] = 75.56},
    ["cannon agile kinetic ammo m"] = {["mass"] = 14.73},
    ["cannon agile kinetic ammo s"] = {["mass"] = 4.10},
    ["cannon agile kinetic ammo xs"] = {["mass"] = 1.61},
    ["cannon agile thermic ammo l"] = {["mass"] = 71.24},
    ["cannon agile thermic ammo m"] = {["mass"] = 12.57},
    ["cannon agile thermic ammo s"] = {["mass"] = 3.20},
    ["cannon agile thermic ammo xs"] = {["mass"] = 1.07},
    ["cannon defense kinetic ammo l"] = {["mass"] = 75.42},
    ["cannon defense kinetic ammo m"] = {["mass"] = 14.66},
    ["cannon defense kinetic ammo s"] = {["mass"] = 4.07},
    ["cannon defense kinetic ammo xs"] = {["mass"] = 1.59},
    ["cannon defense thermic ammo l"] = {["mass"] = 71.10},
    ["cannon defense thermic ammo m"] = {["mass"] = 12.50},
    ["cannon defense thermic ammo s"] = {["mass"] = 2.99},
    ["cannon defense thermic ammo xs"] = {["mass"] = 1.05},
    ["cannon heavy kinetic ammo l"] = {["mass"] = 76.52},
    ["cannon heavy kinetic ammo m"] = {["mass"] = 15.21},
    ["cannon heavy kinetic ammo s"] = {["mass"] = 4.34},
    ["cannon heavy kinetic ammo xs"] = {["mass"] = 1.73},
    ["cannon heavy thermic ammo l"] = {["mass"] = 72.20},
    ["cannon heavy thermic ammo m"] = {["mass"] = 13.05},
    ["cannon heavy thermic ammo s"] = {["mass"] = 3.28},
    ["cannon heavy thermic ammo xs"] = {["mass"] = 1.19},
    ["cannon kinetic ammo l"] = {["mass"] = 76.58},
    ["cannon kinetic ammo m"] = {["mass"] = 14.66},
    ["cannon kinetic ammo s"] = {["mass"] = 3.98},
    ["cannon kinetic ammo xs"] = {["mass"] = 1.54},
    ["cannon l"] = {["mass"] = 15240.00},
    ["cannon m"] = {["mass"] = 2670.00},
    ["cannon precision kinetic ammo l"] = {["mass"] = 75.61},
    ["cannon precision kinetic ammo m"] = {["mass"] = 14.76},
    ["cannon precision kinetic ammo s"] = {["mass"] = 4.11},
    ["cannon precision kinetic ammo xs"] = {["mass"] = 1.54},
    ["cannon precision thermic ammo l"] = {["mass"] = 71.29},
    ["cannon precision thermic ammo m"] = {["mass"] = 12.60},
    ["cannon precision thermic ammo s"] = {["mass"] = 3.20},
    ["cannon precision thermic ammo xs"] = {["mass"] = 1.08},
    ["cannon s"] = {["mass"] = 517.52},
    ["cannon thermic ammo l"] = {["mass"] = 72.37},
    ["cannon thermic ammo m"] = {["mass"] = 12.55},
    ["cannon thermic ammo s"] = {["mass"] = 2.93},
    ["cannon thermic ammo xs"] = {["mass"] = 1.01},
    ["cannon xs"] = {["mass"] = 190.10},
    ["carbon fiber"] = {["mass"] = 1.50},
    ["carbon honeycomb"] = {["mass"] = 22.70},
    ["carbon scrap"] = {["mass"] = 2.27},
    ["carbonfiber honeycomb"] = {["mass"] = 27.38},
    ["catalyst 3"] = {["mass"] = 649.39},
    ["catalyst 4"] = {["mass"] = 606.65},
    ["catalyst 5"] = {["mass"] = 657.68},
    ["chemical industry m"] = {["mass"] = 2300.00},
    ["chromite"] = {["mass"] = 4.54},
    ["chromium honeycomb"] = {["mass"] = 71.90},
    ["chromium scrap"] = {["mass"] = 7.19},
    ["coal"] = {["mass"] = 1.35},
    ["cobalt honeycomb"] = {["mass"] = 89.00},
    ["cobalt scrap"] = {["mass"] = 8.90},
    ["cobaltite"] = {["mass"] = 6.33},
    ["cockpit controller"] = {["mass"] = 1210.00},
    ["columbite"] = {["mass"] = 5.38},
    ["command seat controller"] = {["mass"] = 158.45},
    ["compact aileron m"] = {["mass"] = 1705.00},
    ["compact aileron s"] = {["mass"] = 319.15},
    ["compact aileron xs"] = {["mass"] = 61.20},
    ["concrete honeycomb"] = {["mass"] = 27.57},
    ["concrete"] = {["mass"] = 2.41},
    ["container hub"] = {["mass"] = 55.80},
    ["container l"] = {["mass"] = 14842.70},
    ["container m"] = {["mass"] = 7421.35},
    ["container s"] = {["mass"] = 1281.31},
    ["container xs"] = {["mass"] = 229.09},
    ["copper honeycomb"] = {["mass"] = 89.60},
    ["copper scrap"] = {["mass"] = 8.96},
    ["corner cable model a"] = {["mass"] = 14.10},
    ["corner cable model b"] = {["mass"] = 14.10},
    ["corner cable model c"] = {["mass"] = 14.10},
    ["cryolite"] = {["mass"] = 2.95},
    ["cu-ag alloy"] = {["mass"] = 9.20},
    ["databank"] = {["mass"] = 17.09},
    ["delay line"] = {["mass"] = 7.47},
    ["detection zone l"] = {["mass"] = 7.79},
    ["detection zone m"] = {["mass"] = 7.79},
    ["detection zone s"] = {["mass"] = 7.79},
    ["detection zone xs"] = {["mass"] = 7.79},
    ["dispenser"] = {["mass"] = 2060.00},
    ["dresser"] = {["mass"] = 8.32},
    ["duralumin"] = {["mass"] = 2.80},
    ["dynamic core l"] = {["mass"] = 12140.00},
    ["dynamic core m"] = {["mass"] = 1980.00},
    ["dynamic core s"] = {["mass"] = 375.97},
    ["dynamic core xs"] = {["mass"] = 70.89},
    ["eggplant plant case"] = {["mass"] = 31.90},
    ["electronics industry m"] = {["mass"] = 1620.00},
    ["elevator xs"] = {["mass"] = 207.86},
    ["emergency controller"] = {["mass"] = 9.35},
    ["emitter m"] = {["mass"] = 2040.00},
    ["emitter s"] = {["mass"] = 427.72},
    ["emitter xs"] = {["mass"] = 69.31},
    ["encampment chair"] = {["mass"] = 2.52},
    ["executive chair"] = {["mass"] = 39.62},
    ["exotic antenna l"] = {["mass"] = 11250.00},
    ["exotic antenna m"] = {["mass"] = 2140.00},
    ["exotic antenna xl"] = {["mass"] = 61580.00},
    ["exotic anti-gravity core"] = {["mass"] = 133.06},
    ["exotic anti-matter capsule"] = {["mass"] = 26.73},
    ["exotic anti-matter core unit"] = {["mass"] = 158.05},
    ["exotic casing s"] = {["mass"] = 8.29},
    ["exotic core system s"] = {["mass"] = 28.62},
    ["exotic electronics"] = {["mass"] = 5.77},
    ["exotic magnet"] = {["mass"] = 65.13},
    ["exotic mechanical sensor xs"] = {["mass"] = 102.37},
    ["exotic power system"] = {["mass"] = 82.87},
    ["exotic power transformer l"] = {["mass"] = 5570.00},
    ["exotic processor"] = {["mass"] = 21.47},
    ["exotic quantum alignment unit"] = {["mass"] = 43.24},
    ["exotic quantum core"] = {["mass"] = 11.66},
    ["exotic reinforced frame l"] = {["mass"] = 3260.00},
    ["exotic reinforced frame m"] = {["mass"] = 468.05},
    ["exotic reinforced frame xl"] = {["mass"] = 22780.00},
    ["exotic singularity container"] = {["mass"] = 46.98},
    ["exotic standard frame l"] = {["mass"] = 1420.00},
    ["exotic standard frame xs"] = {["mass"] = 5.20},
    ["expanded gate l"] = {["mass"] = 122750.00},
    ["expanded gate s"] = {["mass"] = 122750.00},
    ["ficus plant a"] = {["mass"] = 31.90},
    ["ficus plant b"] = {["mass"] = 31.90},
    ["flat hover engine l"] = {["mass"] = 1700.00},
    ["fluorine honeycomb"] = {["mass"] = 16.96},
    ["fluorine scrap"] = {["mass"] = 1.70},
    ["fluoropolymer"] = {["mass"] = 1.65},
    ["foliage plant case a"] = {["mass"] = 31.90},
    ["foliage plant case b"] = {["mass"] = 31.90},
    ["force field l"] = {["mass"] = 110.62},
    ["force field m"] = {["mass"] = 110.62},
    ["force field s"] = {["mass"] = 110.62},
    ["force field xs"] = {["mass"] = 207.86},
    ["freight atmospheric engine l"] = {["mass"] = 16930.00},
    ["freight atmospheric engine m"] = {["mass"] = 2980.00},
    ["freight atmospheric engine s"] = {["mass"] = 539.99},
    ["freight atmospheric engine xs"] = {["mass"] = 101.88},
    ["freight space engine l"] = {["mass"] = 22470.00},
    ["freight space engine m"] = {["mass"] = 4090.00},
    ["freight space engine s"] = {["mass"] = 761.74},
    ["freight space engine xl"] = {["mass"] = 126240.00},
    ["freight space engine xs"] = {["mass"] = 146.23},
    ["fuel intake xs"] = {["mass"] = 4.12},
    ["garnierite"] = {["mass"] = 2.60},
    ["gate m"] = {["mass"] = 122750.00},
    ["gate xl"] = {["mass"] = 122750.00},
    ["gate xs"] = {["mass"] = 122750.00},
    ["glass furnace m"] = {["mass"] = 2830.00},
    ["glass panel l"] = {["mass"] = 31.92},
    ["glass panel m"] = {["mass"] = 20.08},
    ["glass panel s"] = {["mass"] = 5.02},
    ["glass"] = {["mass"] = 2.50},
    ["gold coated glass"] = {["mass"] = 3.00},
    ["gold honeycomb"] = {["mass"] = 193.00},
    ["gold nuggets"] = {["mass"] = 19.30},
    ["gold scrap"] = {["mass"] = 19.30},
    ["grade 5 titanium alloy"] = {["mass"] = 4.43},
    ["gunner module l"] = {["mass"] = 11320.00},
    ["gunner module m"] = {["mass"] = 2170.00},
    ["gunner module s"] = {["mass"] = 427.90},
    ["gyroscope"] = {["mass"] = 104.41},
    ["hatch s"] = {["mass"] = 229.09},
    ["headlight"] = {["mass"] = 79.34},
    ["hematite"] = {["mass"] = 5.04},
    ["honeycomb refinery m"] = {["mass"] = 2990.00},
    ["hover engine l"] = {["mass"] = 1700.00},
    ["hover engine m"] = {["mass"] = 302.02},
    ["hover engine s"] = {["mass"] = 56.91},
    ["hovercraft seat controller"] = {["mass"] = 110.33},
    ["hull decorative element a"] = {["mass"] = 14.65},
    ["hull decorative element b"] = {["mass"] = 14.65},
    ["hull decorative element c"] = {["mass"] = 14.65},
    ["illmenite"] = {["mass"] = 4.55},
    ["inconel"] = {["mass"] = 8.50},
    ["infrared laser emitter"] = {["mass"] = 9.93},
    ["infrared laser receiver"] = {["mass"] = 9.93},
    ["interior door"] = {["mass"] = 4200.00},
    ["iron honeycomb"] = {["mass"] = 78.50},
    ["iron scrap"] = {["mass"] = 7.85},
    ["kergon-x1 fuel"] = {["mass"] = 6.00},
    ["kergon-x2 fuel"] = {["mass"] = 6.00},
    ["kergon-x3 fuel"] = {["mass"] = 6.00},
    ["kergon-x4 fuel"] = {["mass"] = 6.00},
    ["keyboard unit"] = {["mass"] = 24.68},
    ["kolbeckite"] = {["mass"] = 2.37},
    ["landing gear l"] = {["mass"] = 8500.00},
    ["landing gear m"] = {["mass"] = 1460.00},
    ["landing gear s"] = {["mass"] = 258.76},
    ["landing gear xs"] = {["mass"] = 49.88},
    ["large atmospheric radar pvp l"] = {["mass"] = 16140.00},
    ["laser agile electromagnetic ammo l"] = {["mass"] = 19.77},
    ["laser agile electromagnetic ammo m"] = {["mass"] = 7.19},
    ["laser agile electromagnetic ammo s"] = {["mass"] = 3.21},
    ["laser agile electromagnetic ammo xs"] = {["mass"] = 31.56},
    ["laser agile thermic ammo l"] = {["mass"] = 12.65},
    ["laser agile thermic ammo m"] = {["mass"] = 3.64},
    ["laser agile thermic ammo s"] = {["mass"] = 1.44},
    ["laser agile thermic ammo xs"] = {["mass"] = 0.67},
    ["laser defense electromagnetic ammo l"] = {["mass"] = 19.62},
    ["laser defense electromagnetic ammo m"] = {["mass"] = 7.12},
    ["laser defense electromagnetic ammo s"] = {["mass"] = 3.18},
    ["laser defense electromagnetic ammo xs"] = {["mass"] = 1.54},
    ["laser defense thermic ammo l"] = {["mass"] = 12.51},
    ["laser defense thermic ammo m"] = {["mass"] = 3.56},
    ["laser defense thermic ammo s"] = {["mass"] = 1.40},
    ["laser defense thermic ammo xs"] = {["mass"] = 0.65},
    ["laser electromagnetic ammo l"] = {["mass"] = 18.70},
    ["laser electromagnetic ammo m"] = {["mass"] = 6.78},
    ["laser electromagnetic ammo s"] = {["mass"] = 3.03},
    ["laser electromagnetic ammo xs"] = {["mass"] = 1.46},
    ["laser emitter"] = {["mass"] = 7.47},
    ["laser heavy electromagnetic ammo l"] = {["mass"] = 20.73},
    ["laser heavy electromagnetic ammo m"] = {["mass"] = 7.67},
    ["laser heavy electromagnetic ammo s"] = {["mass"] = 3.45},
    ["laser heavy electromagnetic ammo xs"] = {["mass"] = 1.68},
    ["laser heavy thermic ammo l"] = {["mass"] = 13.61},
    ["laser heavy thermic ammo m"] = {["mass"] = 3.56},
    ["laser heavy thermic ammo s"] = {["mass"] = 1.68},
    ["laser heavy thermic ammo xs"] = {["mass"] = 0.79},
    ["laser l"] = {["mass"] = 14770.00},
    ["laser m"] = {["mass"] = 2690.00},
    ["laser precision electromagnetic ammo l"] = {["mass"] = 19.81},
    ["laser precision electromagnetic ammo m"] = {["mass"] = 7.22},
    ["laser precision electromagnetic ammo s"] = {["mass"] = 3.23},
    ["laser precision electromagnetic ammo xs"] = {["mass"] = 1.56},
    ["laser precision thermic ammo l"] = {["mass"] = 12.70},
    ["laser precision thermic ammo m"] = {["mass"] = 4.12},
    ["laser precision thermic ammo s"] = {["mass"] = 1.45},
    ["laser precision thermic ammo xs"] = {["mass"] = 0.67},
    ["laser receiver"] = {["mass"] = 9.93},
    ["laser s"] = {["mass"] = 508.26},
    ["laser thermic ammo l"] = {["mass"] = 11.81},
    ["laser thermic ammo m"] = {["mass"] = 3.34},
    ["laser thermic ammo s"] = {["mass"] = 1.31},
    ["laser thermic ammo xs"] = {["mass"] = 0.60},
    ["laser xs"] = {["mass"] = 118.55},
    ["limestone"] = {["mass"] = 2.71},
    ["lithium honeycomb"] = {["mass"] = 5.30},
    ["lithium scrap"] = {["mass"] = 0.53},
    ["long light l"] = {["mass"] = 79.34},
    ["long light m"] = {["mass"] = 79.34},
    ["long light s"] = {["mass"] = 79.34},
    ["long light xs"] = {["mass"] = 70.05},
    ["luminescent white glass"] = {["mass"] = 26.00},
    ["malachite"] = {["mass"] = 4.00},
    ["maneuver atmospheric engine l"] = {["mass"] = 16930.00},
    ["maneuver atmospheric engine m"] = {["mass"] = 2980.00},
    ["maneuver atmospheric engine s"] = {["mass"] = 539.99},
    ["maneuver atmospheric engine xs"] = {["mass"] = 101.88},
    ["maneuver space engine l"] = {["mass"] = 22470.00},
    ["maneuver space engine m"] = {["mass"] = 4090.00},
    ["maneuver space engine s"] = {["mass"] = 761.74},
    ["maneuver space engine xl"] = {["mass"] = 126240.00},
    ["maneuver space engine xs"] = {["mass"] = 146.23},
    ["mangalloy"] = {["mass"] = 7.83},
    ["manganese honeycomb"] = {["mass"] = 72.10},
    ["manganese reinforced glass"] = {["mass"] = 2.90},
    ["manual button s"] = {["mass"] = 13.27},
    ["manual button xs"] = {["mass"] = 13.27},
    ["manual switch"] = {["mass"] = 13.27},
    ["maraging steel"] = {["mass"] = 8.23},
    ["marble honeycomb"] = {["mass"] = 129.40},
    ["marble"] = {["mass"] = 2.70},
    ["medium atmospheric radar pvp m"] = {["mass"] = 2910.00},
    ["metalwork industry m"] = {["mass"] = 2600.00},
    ["military atmospheric engine l"] = {["mass"] = 16930.00},
    ["military atmospheric engine m"] = {["mass"] = 2980.00},
    ["military atmospheric engine s"] = {["mass"] = 539.99},
    ["military atmospheric engine xs"] = {["mass"] = 101.88},
    ["military space engine l"] = {["mass"] = 22470.00},
    ["military space engine m"] = {["mass"] = 4090.00},
    ["military space engine s"] = {["mass"] = 761.74},
    ["military space engine xl"] = {["mass"] = 126240.00},
    ["military space engine xs"] = {["mass"] = 146.23},
    ["missile agile antimatter ammo l"] = {["mass"] = 27.54},
    ["missile agile antimatter ammo m"] = {["mass"] = 6.41},
    ["missile agile antimatter ammo s"] = {["mass"] = 2.16},
    ["missile agile antimatter ammo xs"] = {["mass"] = 0.94},
    ["missile agile kinetic ammo l"] = {["mass"] = 30.99},
    ["missile agile kinetic ammo m"] = {["mass"] = 8.13},
    ["missile agile kinetic ammo s"] = {["mass"] = 3.02},
    ["missile agile kinetic ammo xs"] = {["mass"] = 1.37},
    ["missile antimatter ammo l"] = {["mass"] = 27.90},
    ["missile antimatter ammo m"] = {["mass"] = 6.24},
    ["missile antimatter ammo s"] = {["mass"] = 2.16},
    ["missile antimatter ammo xs"] = {["mass"] = 0.87},
    ["missile defense antimatter ammo l"] = {["mass"] = 6.33},
    ["missile defense antimatter ammo m"] = {["mass"] = 6.33},
    ["missile defense antimatter ammo s"] = {["mass"] = 2.12},
    ["missile defense antimatter ammo xs"] = {["mass"] = 0.92},
    ["missile defense kinetic ammo l"] = {["mass"] = 30.84},
    ["missile defense kinetic ammo m"] = {["mass"] = 8.06},
    ["missile defense kinetic ammo s"] = {["mass"] = 2.99},
    ["missile defense kinetic ammo xs"] = {["mass"] = 1.35},
    ["missile heavy antimatter ammo l"] = {["mass"] = 27.40},
    ["missile heavy antimatter ammo m"] = {["mass"] = 6.89},
    ["missile heavy antimatter ammo s"] = {["mass"] = 2.40},
    ["missile heavy antimatter ammo xs"] = {["mass"] = 1.06},
    ["missile heavy kinetic ammo l"] = {["mass"] = 31.95},
    ["missile heavy kinetic ammo m"] = {["mass"] = 8.61},
    ["missile heavy kinetic ammo s"] = {["mass"] = 3.26},
    ["missile heavy kinetic ammo xs"] = {["mass"] = 1.49},
    ["missile kinetic ammo l"] = {["mass"] = 31.26},
    ["missile kinetic ammo m"] = {["mass"] = 7.92},
    ["missile kinetic ammo s"] = {["mass"] = 2.87},
    ["missile kinetic ammo xs"] = {["mass"] = 1.29},
    ["missile l"] = {["mass"] = 16130.00},
    ["missile m"] = {["mass"] = 2967.50},
    ["missile precision antimatter ammo l"] = {["mass"] = 27.59},
    ["missile precision antimatter ammo m"] = {["mass"] = 6.43},
    ["missile precision antimatter ammo s"] = {["mass"] = 2.17},
    ["missile precision antimatter ammo xs"] = {["mass"] = 0.95},
    ["missile precision kinetic ammo l"] = {["mass"] = 31.04},
    ["missile precision kinetic ammo m"] = {["mass"] = 8.15},
    ["missile precision kinetic ammo s"] = {["mass"] = 3.03},
    ["missile precision kinetic ammo xs"] = {["mass"] = 1.38},
    ["missile s"] = {["mass"] = 593.35},
    ["missile xs"] = {["mass"] = 207.67},
    ["natron"] = {["mass"] = 1.55},
    ["nickel honeycomb"] = {["mass"] = 89.10},
    ["nickel scrap"] = {["mass"] = 8.91},
    ["nightstand"] = {["mass"] = 6.72},
    ["niobium honeycomb"] = {["mass"] = 85.70},
    ["nitron fuel"] = {["mass"] = 4.00},
    ["not operator"] = {["mass"] = 7.47},
    ["office chair"] = {["mass"] = 916.52},
    ["or operator"] = {["mass"] = 7.47},
    ["petalite"] = {["mass"] = 2.41},
    ["pipe a m"] = {["mass"] = 4320.00},
    ["pipe b m"] = {["mass"] = 4320.00},
    ["pipe c m"] = {["mass"] = 4320.00},
    ["pipe connector m"] = {["mass"] = 4320.00},
    ["pipe corner m"] = {["mass"] = 4320.00},
    ["pipe d m"] = {["mass"] = 4320.00},
    ["planet hologram l"] = {["mass"] = 69.90},
    ["planet hologram"] = {["mass"] = 13.39},
    ["plant case a"] = {["mass"] = 21.42},
    ["plant case b"] = {["mass"] = 3.52},
    ["plant case c"] = {["mass"] = 3.52},
    ["plant case d"] = {["mass"] = 3.52},
    ["plant case e"] = {["mass"] = 3.52},
    ["plant case m"] = {["mass"] = 31.90},
    ["plant case s"] = {["mass"] = 31.90},
    ["plant"] = {["mass"] = 3.52},
    ["plastic honeycomb"] = {["mass"] = 27.57},
    ["polycalcite plastic"] = {["mass"] = 1.50},
    ["polycarbonate plastic"] = {["mass"] = 1.40},
    ["polysulfide plastic"] = {["mass"] = 1.60},
    ["pressure tile"] = {["mass"] = 50.63},
    ["programming board"] = {["mass"] = 27.74},
    ["pure aluminium"] = {["mass"] = 2.70},
    ["pure calcium"] = {["mass"] = 1.55},
    ["pure carbon"] = {["mass"] = 2.27},
    ["pure chromium"] = {["mass"] = 7.19},
    ["pure cobalt"] = {["mass"] = 8.90},
    ["pure copper"] = {["mass"] = 8.96},
    ["pure fluorine"] = {["mass"] = 1.70},
    ["pure gold"] = {["mass"] = 19.30},
    ["pure hydrogen"] = {["mass"] = 0.07},
    ["pure iron"] = {["mass"] = 7.85},
    ["pure lithium"] = {["mass"] = 0.53},
    ["pure manganese"] = {["mass"] = 7.21},
    ["pure nickel"] = {["mass"] = 8.91},
    ["pure niobium"] = {["mass"] = 8.57},
    ["pure oxygen"] = {["mass"] = 1.00},
    ["pure scandium"] = {["mass"] = 2.98},
    ["pure silicon"] = {["mass"] = 2.33},
    ["pure silver"] = {["mass"] = 10.49},
    ["pure sodium"] = {["mass"] = 0.97},
    ["pure sulfur"] = {["mass"] = 1.82},
    ["pure titanium"] = {["mass"] = 4.51},
    ["pure vanadium"] = {["mass"] = 6.00},
    ["pyrite"] = {["mass"] = 5.01},
    ["quartz"] = {["mass"] = 2.65},
    ["railgun agile antimatter ammo l"] = {["mass"] = 79.00},
    ["railgun agile antimatter ammo m"] = {["mass"] = 16.45},
    ["railgun agile antimatter ammo s"] = {["mass"] = 4.96},
    ["railgun agile antimatter ammo xs"] = {["mass"] = 2.04},
    ["railgun agile electromagnetic ammo l"] = {["mass"] = 85.24},
    ["railgun agile electromagnetic ammo m"] = {["mass"] = 19.58},
    ["railgun agile electromagnetic ammo s"] = {["mass"] = 6.52},
    ["railgun agile electromagnetic ammo xs"] = {["mass"] = 2.77},
    ["railgun antimatter ammo l"] = {["mass"] = 80.35},
    ["railgun antimatter ammo m"] = {["mass"] = 16.54},
    ["railgun antimatter ammo s"] = {["mass"] = 4.92},
    ["railgun antimatter ammo xs"] = {["mass"] = 2.01},
    ["railgun defense antimatter ammo l"] = {["mass"] = 78.86},
    ["railgun defense antimatter ammo m"] = {["mass"] = 16.38},
    ["railgun defense antimatter ammo s"] = {["mass"] = 4.93},
    ["railgun defense antimatter ammo xs"] = {["mass"] = 2.02},
    ["railgun defense electromagnetic ammo l"] = {["mass"] = 85.10},
    ["railgun defense electromagnetic ammo m"] = {["mass"] = 19.50},
    ["railgun defense electromagnetic ammo s"] = {["mass"] = 6.49},
    ["railgun defense electromagnetic ammo xs"] = {["mass"] = 2.80},
    ["railgun electromagnetic ammo l"] = {["mass"] = 86.40},
    ["railgun electromagnetic ammo m"] = {["mass"] = 19.56},
    ["railgun electromagnetic ammo s"] = {["mass"] = 6.43},
    ["railgun electromagnetic ammo xs"] = {["mass"] = 6.43},
    ["railgun heavy antimatter ammo l"] = {["mass"] = 79.96},
    ["railgun heavy antimatter ammo m"] = {["mass"] = 16.93},
    ["railgun heavy antimatter ammo s"] = {["mass"] = 5.20},
    ["railgun heavy antimatter ammo xs"] = {["mass"] = 2.16},
    ["railgun heavy electromagnetic ammo l"] = {["mass"] = 86.20},
    ["railgun heavy electromagnetic ammo m"] = {["mass"] = 20.06},
    ["railgun heavy electromagnetic ammo s"] = {["mass"] = 6.76},
    ["railgun heavy electromagnetic ammo xs"] = {["mass"] = 2.94},
    ["railgun l"] = {["mass"] = 16720.00},
    ["railgun m"] = {["mass"] = 3007.00},
    ["railgun precision antimatter ammo l"] = {["mass"] = 79.05},
    ["railgun precision antimatter ammo m"] = {["mass"] = 16.48},
    ["railgun precision antimatter ammo s"] = {["mass"] = 4.97},
    ["railgun precision antimatter ammo xs"] = {["mass"] = 2.05},
    ["railgun precision electromagnetic ammo l"] = {["mass"] = 85.29},
    ["railgun precision electromagnetic ammo m"] = {["mass"] = 19.60},
    ["railgun precision electromagnetic ammo s"] = {["mass"] = 6.53},
    ["railgun precision electromagnetic ammo xs"] = {["mass"] = 2.83},
    ["railgun s"] = {["mass"] = 599.53},
    ["railgun xs"] = {["mass"] = 232.02},
    ["rare anti-gravity core"] = {["mass"] = 123.22},
    ["rare anti-matter capsule"] = {["mass"] = 25.80},
    ["rare casing s"] = {["mass"] = 8.57},
    ["rare casing xs"] = {["mass"] = 1.52},
    ["rare core system l"] = {["mass"] = 783.65},
    ["rare electronics"] = {["mass"] = 5.63},
    ["rare laser chamber s"] = {["mass"] = 90.49},
    ["rare magnet"] = {["mass"] = 64.40},
    ["rare optics"] = {["mass"] = 10.70},
    ["rare power system"] = {["mass"] = 78.31},
    ["rare power transformer l"] = {["mass"] = 5570.00},
    ["rare power transformer xl"] = {["mass"] = 30540.00},
    ["rare quantum core"] = {["mass"] = 11.66},
    ["rare reinforced frame l"] = {["mass"] = 3370.00},
    ["rare reinforced frame xl"] = {["mass"] = 23540.00},
    ["rare singularity container"] = {["mass"] = 46.58},
    ["rare standard frame l"] = {["mass"] = 1050.00},
    ["receiver m"] = {["mass"] = 6636.91},
    ["receiver s"] = {["mass"] = 475.87},
    ["receiver xs"] = {["mass"] = 13.27},
    ["recycler m"] = {["mass"] = 2350.00},
    ["red gold"] = {["mass"] = 14.13},
    ["refiner m"] = {["mass"] = 2300.00},
    ["reinforced sliding door"] = {["mass"] = 4200.00},
    ["relay"] = {["mass"] = 8.87},
    ["remote controller"] = {["mass"] = 7.79},
    ["repair unit"] = {["mass"] = 400.00},
    ["resurrection node"] = {["mass"] = 728.43},
    ["retro-rocket brake l"] = {["mass"] = 3770.00},
    ["retro-rocket brake m"] = {["mass"] = 714.00},
    ["retro-rocket brake s"] = {["mass"] = 137.55},
    ["rhodonite"] = {["mass"] = 3.76},
    ["rocket engine l"] = {["mass"] = 3390.00},
    ["rocket engine m"] = {["mass"] = 680.05},
    ["rocket engine s"] = {["mass"] = 2223.76},
    ["rocket fuel tank l"] = {["mass"] = 25740.00},
    ["rocket fuel tank m"] = {["mass"] = 6231.00},
    ["rocket fuel tank s"] = {["mass"] = 886.72},
    ["rocket fuel tank xs"] = {["mass"] = 173.42},
    ["round carpet"] = {["mass"] = 2.78},
    ["safe atmospheric engine l"] = {["mass"] = 16930.00},
    ["safe atmospheric engine m"] = {["mass"] = 2980.00},
    ["safe atmospheric engine s"] = {["mass"] = 539.99},
    ["safe atmospheric engine xs"] = {["mass"] = 101.88},
    ["safe space engine l"] = {["mass"] = 22470.00},
    ["safe space engine m"] = {["mass"] = 4090.00},
    ["safe space engine s"] = {["mass"] = 761.74},
    ["safe space engine xl"] = {["mass"] = 126240.00},
    ["safe space engine xs"] = {["mass"] = 146.23},
    ["salad plant case"] = {["mass"] = 31.90},
    ["sc-al alloy"] = {["mass"] = 2.85},
    ["scandium honeycomb"] = {["mass"] = 29.85},
    ["scandium scrap"] = {["mass"] = 2.98},
    ["screen m"] = {["mass"] = 18.67},
    ["screen s"] = {["mass"] = 18.67},
    ["screen xl"] = {["mass"] = 12810.00},
    ["screen xs"] = {["mass"] = 18.67},
    ["sensors s"] = {["mass"] = 28.00},
    ["shelf empty"] = {["mass"] = 8.32},
    ["shelf full"] = {["mass"] = 8.32},
    ["shelf half full"] = {["mass"] = 8.32},
    ["shower unit"] = {["mass"] = 25.62},
    ["sign l"] = {["mass"] = 18.67},
    ["sign m"] = {["mass"] = 18.67},
    ["sign s"] = {["mass"] = 18.67},
    ["sign xs"] = {["mass"] = 18.67},
    ["silicon honeycomb"] = {["mass"] = 23.30},
    ["silicon scrap"] = {["mass"] = 2.33},
    ["silumin"] = {["mass"] = 3.00},
    ["silver honeycomb"] = {["mass"] = 104.90},
    ["silver scrap"] = {["mass"] = 10.49},
    ["sink unit"] = {["mass"] = 6.72},
    ["sliding door m"] = {["mass"] = 1010.00},
    ["sliding door s"] = {["mass"] = 749.15},
    ["small atmospheric radar pvp s"] = {["mass"] = 486.72},
    ["smelter m"] = {["mass"] = 2060.00},
    ["sodium honeycomb"] = {["mass"] = 9.70},
    ["sodium scrap"] = {["mass"] = 0.97},
    ["sofa"] = {["mass"] = 39.62},
    ["space core l"] = {["mass"] = 7680.00},
    ["space core m"] = {["mass"] = 3040.00},
    ["space core s"] = {["mass"] = 459.57},
    ["space core xs"] = {["mass"] = 38.99},
    ["space engine l"] = {["mass"] = 22470.00},
    ["space engine m"] = {["mass"] = 4090.00},
    ["space engine s"] = {["mass"] = 761.74},
    ["space engine xl"] = {["mass"] = 126240.00},
    ["space engine xs"] = {["mass"] = 146.23},
    ["space fuel tank l"] = {["mass"] = 5480.00},
    ["space fuel tank m"] = {["mass"] = 988.67},
    ["space fuel tank s"] = {["mass"] = 182.67},
    ["space radar l"] = {["mass"] = 12490.00},
    ["space radar m"] = {["mass"] = 2350.00},
    ["space radar s"] = {["mass"] = 486.72},
    ["spaceship hologram l"] = {["mass"] = 14.02},
    ["spaceship hologram m"] = {["mass"] = 15.98},
    ["spaceship hologram s"] = {["mass"] = 112.72},
    ["square carpet"] = {["mass"] = 2.52},
    ["square light l"] = {["mass"] = 79.34},
    ["square light m"] = {["mass"] = 79.34},
    ["square light s"] = {["mass"] = 79.34},
    ["square light xs"] = {["mass"] = 70.05},
    ["squash plant case"] = {["mass"] = 31.90},
    ["stabilizer l"] = {["mass"] = 11500.00},
    ["stabilizer m"] = {["mass"] = 2030.00},
    ["stabilizer s"] = {["mass"] = 366.89},
    ["stabilizer xs"] = {["mass"] = 69.88},
    ["stainless steel"] = {["mass"] = 7.75},
    ["static core l"] = {["mass"] = 10700.00},
    ["static core m"] = {["mass"] = 1930.00},
    ["static core s"] = {["mass"] = 360.18},
    ["static core xs"] = {["mass"] = 70.89},
    ["steel column"] = {["mass"] = 13.37},
    ["steel honeycomb"] = {["mass"] = 115.14},
    ["steel panel"] = {["mass"] = 13.37},
    ["steel"] = {["mass"] = 8.05},
    ["sulfur honeycomb"] = {["mass"] = 18.19},
    ["sulfur scrap"] = {["mass"] = 1.82},
    ["surrogate pod station"] = {["mass"] = 569.52},
    ["suspended fruit plant"] = {["mass"] = 3.52},
    ["suspended plant a"] = {["mass"] = 3.52},
    ["suspended plant b"] = {["mass"] = 3.52},
    ["table"] = {["mass"] = 264.32},
    ["telemeter"] = {["mass"] = 40.79},
    ["territory scanner"] = {["mass"] = 66460.00},
    ["territory unit"] = {["mass"] = 20050.00},
    ["ti-nb supraconductor"] = {["mass"] = 10.10},
    ["titanium honeycomb"] = {["mass"] = 45.10},
    ["toilet unit a"] = {["mass"] = 6.72},
    ["toilet unit b"] = {["mass"] = 6.72},
    ["transfer unit"] = {["mass"] = 10150.00},
    ["transparent screen l"] = {["mass"] = 18.67},
    ["transparent screen m"] = {["mass"] = 18.67},
    ["transparent screen s"] = {["mass"] = 18.67},
    ["transparent screen xs"] = {["mass"] = 18.67},
    ["trash"] = {["mass"] = 6.72},
    ["uncommon antenna l"] = {["mass"] = 9240.00},
    ["uncommon antenna m"] = {["mass"] = 1770.00},
    ["uncommon antenna s"] = {["mass"] = 379.20},
    ["uncommon antenna xs"] = {["mass"] = 117.16},
    ["uncommon anti-matter capsule"] = {["mass"] = 24.32},
    ["uncommon burner"] = {["mass"] = 49.40},
    ["uncommon casing l"] = {["mass"] = 377.65},
    ["uncommon casing m"] = {["mass"] = 54.25},
    ["uncommon casing s"] = {["mass"] = 8.05},
    ["uncommon casing xl"] = {["mass"] = 2640.00},
    ["uncommon casing xs"] = {["mass"] = 1.45},
    ["uncommon combustion chamber l"] = {["mass"] = 9210.00},
    ["uncommon combustion chamber m"] = {["mass"] = 1730.00},
    ["uncommon combustion chamber s"] = {["mass"] = 366.33},
    ["uncommon combustion chamber xs"] = {["mass"] = 112.07},
    ["uncommon component"] = {["mass"] = 2.34},
    ["uncommon connector"] = {["mass"] = 3.90},
    ["uncommon core system l"] = {["mass"] = 737.10},
    ["uncommon core system m"] = {["mass"] = 28.08},
    ["uncommon core system s"] = {["mass"] = 28.08},
    ["uncommon electric engine xl"] = {["mass"] = 50800.00},
    ["uncommon electronics"] = {["mass"] = 5.34},
    ["uncommon explosive module"] = {["mass"] = 19.04},
    ["uncommon fixation"] = {["mass"] = 1.16},
    ["uncommon hydraulics"] = {["mass"] = 28.35},
    ["uncommon injector"] = {["mass"] = 20.50},
    ["uncommon ionic chamber l"] = {["mass"] = 11010.00},
    ["uncommon ionic chamber m"] = {["mass"] = 2100.00},
    ["uncommon ionic chamber s"] = {["mass"] = 452.35},
    ["uncommon ionic chamber xl"] = {["mass"] = 60120.00},
    ["uncommon ionic chamber xs"] = {["mass"] = 140.80},
    ["uncommon laser chamber xs"] = {["mass"] = 24.80},
    ["uncommon led"] = {["mass"] = 1.27},
    ["uncommon light s"] = {["mass"] = 28.80},
    ["uncommon light xs"] = {["mass"] = 7.84},
    ["uncommon magnet"] = {["mass"] = 62.10},
    ["uncommon optics"] = {["mass"] = 9.94},
    ["uncommon ore scanner xl"] = {["mass"] = 1870.00},
    ["uncommon pipe"] = {["mass"] = 2.32},
    ["uncommon power system"] = {["mass"] = 62.40},
    ["uncommon power transformer m"] = {["mass"] = 1030.00},
    ["uncommon power transformer s"] = {["mass"] = 221.56},
    ["uncommon processor"] = {["mass"] = 15.56},
    ["uncommon quantum core"] = {["mass"] = 11.04},
    ["uncommon reinforced frame l"] = {["mass"] = 3230.00},
    ["uncommon reinforced frame m"] = {["mass"] = 464.80},
    ["uncommon reinforced frame s"] = {["mass"] = 69.16},
    ["uncommon reinforced frame xl"] = {["mass"] = 22620.00},
    ["uncommon reinforced frame xs"] = {["mass"] = 12.64},
    ["uncommon screen l"] = {["mass"] = 671.24},
    ["uncommon screen xl"] = {["mass"] = 3860.00},
    ["uncommon screen xs"] = {["mass"] = 7.29},
    ["uncommon screw"] = {["mass"] = 7.90},
    ["uncommon singularity container"] = {["mass"] = 44.88},
    ["uncommon solid warhead"] = {["mass"] = 45.36},
    ["uncommon standard frame l"] = {["mass"] = 1030.00},
    ["uncommon standard frame m"] = {["mass"] = 148.54},
    ["uncommon standard frame s"] = {["mass"] = 22.12},
    ["uncommon standard frame xs"] = {["mass"] = 4.06},
    ["urinal unit"] = {["mass"] = 8.32},
    ["vanadinite"] = {["mass"] = 6.95},
    ["vanadium honeycomb"] = {["mass"] = 60.00},
    ["vanamer"] = {["mass"] = 1.57},
    ["vertical booster l"] = {["mass"] = 2820.00},
    ["vertical booster m"] = {["mass"] = 530.60},
    ["vertical booster s"] = {["mass"] = 102.00},
    ["vertical booster xs"] = {["mass"] = 22.70},
    ["vertical light l"] = {["mass"] = 79.34},
    ["vertical light m"] = {["mass"] = 79.34},
    ["vertical light s"] = {["mass"] = 79.34},
    ["vertical light xs"] = {["mass"] = 70.05},
    ["vertical sign l"] = {["mass"] = 18.67},
    ["vertical sign m"] = {["mass"] = 18.67},
    ["vertical sign xs"] = {["mass"] = 18.67},
    ["vertical wing"] = {["mass"] = 20.30},
    ["virtual scaffolding projector"] = {["mass"] = 167.11},
    ["wardrobe"] = {["mass"] = 39.62},
    ["warp beacon xl"] = {["mass"] = 148940.00},
    ["warp cell"] = {["mass"] = 100.00},
    ["warp drive l"] = {["mass"] = 31360.00},
    ["window l"] = {["mass"] = 378.56},
    ["window m"] = {["mass"] = 189.28},
    ["window s"] = {["mass"] = 94.64},
    ["window xs"] = {["mass"] = 47.32},
    ["wing m"] = {["mass"] = 1700.00},
    ["wing s"] = {["mass"] = 319.15},
    ["wing tip l"] = {["mass"] = 127.75},
    ["wing tip m"] = {["mass"] = 20.30},
    ["wing tip s"] = {["mass"] = 20.30},
    ["wing variant m"] = {["mass"] = 1700.00},
    ["wing xs"] = {["mass"] = 61.20},
    ["wood honeycomb"] = {["mass"] = 27.19},
    ["wood"] = {["mass"] = 0.60},
    ["wooden armchair"] = {["mass"] = 1.72},
    ["wooden chair"] = {["mass"] = 2.52},
    ["wooden dresser"] = {["mass"] = 34.02},
    ["wooden low table"] = {["mass"] = 5.92},
    ["wooden sofa"] = {["mass"] = 39.62},
    ["wooden table l"] = {["mass"] = 34.02},
    ["wooden table m"] = {["mass"] = 34.02},
    ["wooden wardrobe"] = {["mass"] = 39.62},
    ["xeron fuel"] = {["mass"] = 0.80}
}



function getItemInformation(name, parameter)
    if itemsTable[name:lower()] == nil or itemsTable[name:lower()] == "" then
        system.printDanger("Item " .. name .. " unknown. Please check Library.start() for allowed items.")
        return nil
    else
        if parameter ~= nil or parameter ~= "" then
            return itemsTable[name:lower()][parameter]
        else
            return itemsTable[name:lower()]
        end
    end
end



function getElementObject(name)
    if unit[name] == nil then
        system.printDanger("Element" .. name .. " unknown. Please check slot name on left side of the LUA editor.")
        return nil
    else
        return unit[name]
    end
end



function getHTMLBody(name, price, amount, batch, batchSize, special, specialText)
    local returnValue = {}
    
    -- Define default layout parameters
    local paddingTop = 5
    local paddingBottom = 5
    local fontSize = 10

    -- Specialize layout parameters
    if batch and special then
        paddingBottom = 4
        fontSize = 7
    elseif batch then
        fontSize = 9
    elseif special then
        paddingBottom = 4
        fontSize = 8
    end


    if batch then
        price = [[<div style="padding-top:]] .. paddingTop .. [[vw; color:white">]] .. price .. [[<br>(]] .. batchSize .. [[ per batch)</div>]]
    else
        price = [[<div style="padding-bottom:]] .. paddingBottom .. [[vw; color:white">]] .. price .. [[</div>]]
    end
    
    if amount > 0 then
        if batch then
            amount = [[<div style="padding-top:]] .. paddingTop .. [[vw;">Stock:]] .. math.floor(amount/batchSize) .. [[</div>]]
        else
            amount = [[<div style="padding-top:]] .. paddingTop .. [[vw;">Stock:]] .. amount .. [[</div>]]
        end
    else
        amount = [[<div style="padding-top:]] .. paddingTop .. [[vw; color:red">OUT OF STOCK</div>]]
    end
    
    
    returnValue[#returnValue + 1] = [[<div style="font-size:]] .. fontSize .. [[vw; font-weight: bold; color:yellow">]]
    returnValue[#returnValue + 1] = [[<center>]]
    if special then
         returnValue[#returnValue + 1] = [[<div style="padding-bottom:]] .. paddingBottom .. [[vw; font-size:]] .. (fontSize+3) .. [[vw; color:red">]] .. specialText ..[[</div>]]
    end
    returnValue[#returnValue + 1] = [[<div>]] .. name .. [[</div>]]
    returnValue[#returnValue + 1] = [[<div>]] .. price .. [[</div>]]
    returnValue[#returnValue + 1] = amount
    returnValue[#returnValue + 1] = [[</center>]]
    returnValue[#returnValue + 1] = [[</div>]]
    
    return  returnValue
end



function format_number(n) -- credit http://richard.warburton.it
    local left,num,right = string.match(n,'^([^%d]*%d)(%d*)(,-)$')
    return left..(num:reverse():gsub('(%d%d%d)','%1.'):reverse()) .. right .. 'H'
end



function round(num, numDecimalPlaces)
    local mult = 10 ^ (numDecimalPlaces or 0)
    if numDecimalPlaces ~= nil then
        return math.floor(num * mult + 0.5) / mult
    else
        return math.floor((num * mult + 0.5) / mult)
    end
end



-- credit Jericho's system.print() extension 
-- https://github.com/Jericho1060/du-storage-monitoring
system.printColor = function(message, color) system.print('<span style="color:' .. color .. '; font-weight: bold;">' .. message .. '</span>') end
system.printSuccess = function (message) system.printColor(message, "#28a745") end
system.printDanger = function (message) system.printColor(message, "red") end
system.printWarning = function (message) system.printColor(message, "#ffc107") end
system.printInfo = function (message) system.printColor(message, "#17a2b8") end